#include <string>
#include <vector>
#include <sys/wait.h>
#include <sys/stat.h>
#include <bits/stdc++.h>
#include <fstream>
#include <unistd.h>
#include <dirent.h>
#include <stdlib.h>
#include <iostream>
#include <sstream>
#include <iomanip>
#include <stdio.h>
#include <string.h>
#include <fcntl.h>
#include <sys/types.h>