all: EnsembleClassifier voter linearClassifier





EnsembleClassifier:
	g++ EnsembleClassifier.cpp -o EnsembleClassifier.out

voter:
	g++ voter.cpp -o voter.out

linearClassifier:
	g++ linearClassifier.cpp -o linearClassifier.out

rm:
	rm -rf *.out 